### ISSUE TITLE
Broker clustering

### ISSUE THREAD

**Issue by maustin75** [ah-/rdkafka-dotnet#12]
We are testing the producer with 3 brokers. If we stop one broker service, it seems that the producer is round-robin based and if it hits that down broker, it hangs. Does the producer recognize that the broker is down and just handle it? Is there some setting other than defaults that we need to configure?

**Comment by ah-** [comment]
If the broker goes down the partitions assigned to that broker should get reassigned and then the producer should switch over.

If you set the debug config to broker,topic (var config = new Config(), config["debug"] = "broker,topic" and pass that into the Producer ctor) you will get lots of useful details about what exactly is going on.
Could you try reproducing with more logging enabled and paste the output?

**Comment by maustin75** [comment]
Thanks. I have not tried this yet but I will when I get into the office tomorrow. I also wanted to mention that this is a web application and I'm keeping the producer instance across web requests using unity but I'm recreating the topic on each request before calling publish. Is this a problem?

**Comment by maustin75** [comment]
Hi Andreas,
It seems that when a broker goes down the awaiting of topic.publish hangs. I'm curious why in the example you use deliveryReport.ContinueWith( instead of await or if it's even recommended to use "await topic.produce()"? My ack is "-1."?

Also, I have logging now and if a broker goes down it gives a reconnecting error continuously. I'm thinking that might be ok since it maybe should keep trying to connect for a period of time?

Thanks

**Comment by ah-** [comment]
Hi,

It's using .ContinueWith so it will send out other messages while the first one is still in flight. I'd very much recommend to only use await topic.Produce if you already have parallelism in the Task that calls the Produce. If you have only one thread producing messages and it awaits every single message individually then latency will kill your performance.
The Task you get back from a Produce(message) corresponds to the sending of that message. It might take considerable time to complete if a broker is down, as it'll try to reconnect and only give up after message.timeout.ms, which is 5 minutes by default. If you're awaiting that Task before you do anything else it'll block everything for up to 5 minutes, and ContinueWith is just one convenient option of continuing to do other things.

It should keep reconnecting, so that part sounds fine.

Interesting that it behaves differently when running under Unity vs. a console app. Are you maybe running in some kind of deadlock? Is the threadpool full by any chance?

**Comment by maustin75** [comment]
What happens as soon as a broker goes down? Is below correct?
1. Broker 1 goes down
2. Messages sent to broker 1 gets queued for 5 minutes default trying to get to Broker 1
3. Messages still get sent to broker 1, 2, and 3 (round-robin) with messages to broker 2 and 3 making it to consumers but broker 1 queuing.
4. 5 minutes is up and messages for broker 1 either error and get lost or messages finally make it to broker 1?

Thanks

**Comment by ah-** [comment]
I think those consumer errors are just the java client complaining about the broker going down, so nothing too useful in there. More logs from librdkafka using the debug config would be useful.

About the produce behaviour on brokers going down, I'd recommend asking at the upstream project https://github.com/edenhill/librdkafka, just open an issue there and I'm sure @edenhill will be able to tell you exactly what it is doing.
I think your understanding of the behaviour is roughly correct though.

What exactly is Unity/Web? It stopping writes to all brokers sounds weird, so I'd be interested in why that happens. How does it differ from your console app?

**Comment by maustin75** [comment]
Thanks. Unity is used in asp.net: https://github.com/unitycontainer/unity as a dependency injection container. I guess one of my main questions now is how to detect that a producer has an error or needs to be recycled or recreated. We have a health service that is attempting to make sure we can still write to kafka and I'm not sure how to get results.

Also, is there a way to say restart or refresh the producer connection for the client?

**Comment by ah-** [comment]
Oh interesting, does unity by any chance create rdkafka objects per request? They're designed to be created and then used for a while.

All refreshing and so on is done internally. If you find a case where this isn't true then that's probably a bug.

I think the closest thing to health events currently is to install a custom logger, there's an error callback in librdkafka but that's not exposed yet.

**Comment by ah-** [comment]
Closing to clean up, feel free to reopen if this is still an issue.
