### ISSUE TITLE
lost messages

### ISSUE THREAD

**Issue by srikanth-av** [ah-/rdkafka-dotnet#14]
Hi,

I have found that lost my data in below scenario's.

case 1:   
created two processes to consume messages, the message are distributed properly. I lost message when i stop one of the process.

case 2:
created a consumer(single process) to consume message, i did not received old message when I stop  and start consumer.

Pls help me on this.

**Comment by ah-** [comment]
Hey, 

by data lost you mean that your consumer did not get all messages? So in case 2, you run a consumer which gets messages up to e.g. offset 100 on one partition, then you restart it and it continues at offset 110 and then the messages in between never arrived?

Do you think you could build a simple test case that reproduces your problem reliably with as little code as possible?

There are a couple of possible issues I could imagine. Once you have the minimal test case, could you try disabling automatic offset commits and handle them manually? Set config["enable.auto.commit"] = "false" and call consumer.Commit(message) yourself every once in a while.

**Comment by srikanth-av** [comment]
Hi

In case 2, Yes. I observed that the messages in between 100 and 110 never arrived. I have attached sample consumer code(ConsumerExample.txt) for the same.
In case 1, i got the message after some time.

[ConsumerExample.txt](https://github.com/ah-/rdkafka-dotnet/files/206176/ConsumerExample.txt)

**Comment by ah-** [comment]
I just updated the librdkafka version used, there's a slim chance that fixed a bug, but otherwise I can't see the same exact problems when I try running your example.

Can you help me a bit with reproducing?

So for case 2:
I've created a new topic with just one partition for simplicity using `./kafka-topics.sh --zookeeper localhost --create --topic issue14 --partitions 1 --replication-factor 1`.
Then I've started the SimpleProducer with `dnx  run 127.0.0.1:9092 issue14` and the first consumer of your example (https://gist.github.com/ah-/ad7a575c4970c2ec1ddc8caa1370fcf9) with `dnx  run 127.0.0.1:9092 issue14`.
At this point I published some messages, which arrived nicely, up to offset 70. Then I stopped the consumer, produced messages up to offset 80, and then started the consumer again, and it picked up messages 70-80.

If you do the same, do you see the same behaviour? This appears to be working for me, so I must be something differently.

For case 1:
Can you describe the exact steps to reproduce? Are both consumers in the same consumer group or in different ones?
If they're in the same group, there is a short time during the rebalance where consumers don't receive messages. They should arrive once the rebalance has completed. Do the messages arrive if you just wait for a couple more seconds?

**Comment by srikanth-av** [comment]
Hi,

now i'm not able to reproduce those issues.
case 1, both the consumers are in same group. here each consumer is processing in a order.
eg.
consumer1 | consumer2
-------------   |  -------------
msg0          |   msg1
msg2          |   msg3
msg4

I stopped consumer2 after msg4 was consumed...

case 2, now i'm seeing the same behavior, consumer picking messages 70-80.
**topic configuration:**
bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 3 --partitions 4 --topic MyTest

**Comment by ah-** [comment]
Ok, that sounds all good. If you do manage to reproduce it can you reopen this issue?
