### ISSUE TITLE
bulk send support 

### ISSUE THREAD

**Issue by avoxm** [ah-/rdkafka-dotnet#19]
It looks like currently topic.Produce processes one message at a time. This is very slow when you need to process millions of records. Is there a way to bulk send data to kafka ?

**Comment by ah-** [comment]
The trick is to not immediately await the send but to have multiple in flight. librdkafka will batch up your messages and send them in bulk for you, automatically.

You're not the first to ask this question, so I wonder if it would make sense to add a convenience wrapper that calls produce multiple times for you internally.

How do you think the batch interface should look like? In particular, how would it return the result of the batch produce operation?

Say you call `var result = topic.Produce(messages)`, then some of the messages could succeed, and some could fail. Any opinion what the type of result should be?

**Comment by avoxm** [comment]
That's what I figured, because when I removed await the performance went up. The problem with this is as you have pointed out is that there is no feedback on whether  the batch was executed or it fails.

**Comment by avoxm** [comment]
Interface can be something like : 

`Task<void> Produce(IEnumerable<byte[]> payload, byte[] key = null, int partition = -1);`

**Comment by avoxm** [comment]
As an alternative interface can be the same and send messages one by one but keep the connection stream open and throw exception only when there is a network issue or it fails to send the messages.  

Something like this where `topic.Produce` does not get the report or anything, it just makes sure data was sent through network.
 
`           using (Producer producer = new Producer(config, "host:9092"))
            using (Topic topic = producer.Topic(topicName, topicConfig))
            {
                foreach (var i in Enumerable.Range(1, 1000000))
                {
                    byte[] data = Encoding.UTF8.GetBytes(message + i.ToString());
                    topic.Produce(data, key);
                }
            }`

**Comment by ah-** [comment]
Looking at the Java client docs at https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html it seems they don't support batch produces either. Their interface is basically exactly the same we have right now.

I think your last snippet is exactly the way to go and will work right now.
Each Produce in the loop just enqueues the operation.
There is an upper limit to the produce queue size (queue.buffering.max.messages, see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md), one that has been reached Produce() will block until some messages have been processed.

The Dispose() of the producer ensures that all produce requests have been handled, so either they've been delivered or they have definitely errored out (e.g. because of a timeout or broker error).

You can even add `topic.Produce(data).ContinueWith(var dr => Console.WriteLine($"{dr.Offset}"))` or so to get nonblocking async feedback.

**Comment by avoxm** [comment]
Interesting... I will experiment and update the issue accordingly. As long as there is a way to make sure that data was delivered through network, that will be enough.

**Comment by avoxm** [comment]
When I run 

`topic.Produce(data, key).ContinueWith(dr => Console.WriteLine($"Produced to Partition: {dr.Result.Partition}, Offset: {dr.Result.Offset}"));`

Offset is always 0

**Comment by ah-** [comment]
That might be config["produce.offset.report"] not being "true". There's some code to always set it in Topic.cs because for whatever reason it is "false" by default in librdkafka.

How are you creating the topic and what TopicConfig does it use?

**Comment by avoxm** [comment]
Yes it was missing value in TopicConfig. I needed to enable `request.required.acks`.

**Comment by ah-** [comment]
I think for throughput without caring too much about transactional semantics/ordering between messages this is solved by the current interface, so closing.

https://github.com/edenhill/librdkafka/issues/204 tracks upsteam support for transactional batches, would love to implement that once it becomes available.
