### ISSUE TITLE
How to detect that all brokers are down?

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#23]
I need to try and connect to a different cluster in the event that consuming from local cluster is not possible because all brokers are down. 

If i shut down all brokers then EventConsumer.OnError is not raised. However, the log callback passed to Config.Logger is called with a message like " 3/3 brokers are down". Should i parse the string in the log callback to detect this?

I see the API has an error code: ErrorCode._ALL_BROKERS_DOWN.
How can i receive this event?

**Comment by ah-** [comment]
The basic error handling philosophy behind librdkafka is to keep trying on recoverable errors. So Consumer.OnError only gets notified if something really bad has happened, brokers going down is something that it wants to handle gracefully.

However, librdkafka does expose an error_cb that would make it possible to get a proper notification instead of just the log message.

See https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L945 and https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L2031.
That would give you the ErrorCode instead of the log message. I might have a look into exposing that.

**Comment by ah-** [comment]
Give RdKafka 0.9.1-ci-93 a try, should now raise the _ALL_BROKERS_DOWN event after a timeout.

**Comment by MaximGurschi** [comment]
Again, very quick of you! It works as expected thank you!

Can I clarify one thing though? If my use case is:
1.cluster DC1 and cluster DC2
2.producer/consumer connected to DC1
3.when DC1 is completely unavailable (by this i mean all brokers) then have producer/consumer connect to DC2

In this scenario, to achieve 3, is it correct to:
a.detect all DC1 brokers down and explicitly connect to DC2? or,
b.(wishful thinking) I can provide both DC1 and DC2 brokers as the "brokerlist" parameter (when instantiating producer/consumer) and it will work correctly during fail-over to DC2? I would think the producer might work as expected but that the consumer might need to consider the offsets it uses when switching to DC2...

**Comment by ah-** [comment]
Happy to help when I get detailed questions or useful bug reports!

One Producer deals with one Kafka cluster, so you'll have to create two Producers and then switch between them yourself. What kind of delivery guarantees do you need?
I think that failover is too application specific to be able to provide a generic solution that would make everyone happy.

Pinging @edenhill, he might have some more input on how to handle DC failover best.

**Comment by MaximGurschi** [comment]
Thanks for that. I believe you have answered my question by this:

> One Producer deals with one Kafka cluster
