### ISSUE TITLE
Handle.Dispose takes a long time

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#25]
Thank you for adding the feature to detect that all brokers are down.

Once i detect that all brokers are down, i clean up the producer by calling Producer.Dispose. This seems to block for an indefinite time. Is this expected or is this not a concern and i should just not dispose?

Scenario:
1.No brokers are available - keep it that way.
2.Instantiate producer in thread T1.
3.Register for the Producer.OnError event. Do some work in here (Thread.Sleep).
4.Call Producer.Dispose in thread T1.

This is the test method:
private static void Test(string brokerList)
{
	var producer = new Producer(new Config(), brokerList);
	producer.OnError += (sender, args) => { Thread.Sleep(100); };

	Console.WriteLine("Call dispose");
	var stw = Stopwatch.StartNew();
	producer.Dispose();
	stw.Stop();

	Console.WriteLine("Time needed to dispose: " + stw.Elapsed);
	Console.ReadKey();
}

I have also noticed that it takes exponential time for the Producer.Dispose to return the more time i put in Thread.Sleep. Here are some stats:
SleepSec DisposeSec
0.1->0.3040613
0.15->1.0052943
0.2->1.0062785
0.25->2.7257917
0.3->3.7156785
0.305->11.4095752

Should i aim at exiting the callback as soon as possible?

**Comment by ah-** [comment]
I think for your use case you should probably just keep both Producers up.

That said, it's still interesting to look at what's going on.
The Dispose() first makes sure that all outstanding events of the Producer have been processed, so if you had a produce request in-flight and then called Dispose(), it would block until that produce request has either completed or timed out.

What I suspect happens is that during the Dispose() OnError gets multiple times (haven't checked, but i'd suspect at least one connection timeout to the broker and then with the all brokers down event). So there you're already not sleeping for 100ms but a multiple of that. And then I suspect it explodes because during the time that it was waiting in the Sleep librdkafka tried reconnecting, failed and triggered another round of OnError.

At least that's my guess, if you really want to know I'd add some logging to OnError and set debug=all in the config.

**Comment by edenhill** [comment]
If youve produced messages that havent been sent to or acked by the broker yet, those messages will linger in the internal queues for message.timeout.ms (5min default), which could be the reason for what seems like an indefinite time.

**Comment by MaximGurschi** [comment]
Thanks for the feedback! The method i have placed above is the exact and only thing i run from Main. As you see i do not produce any messages.

I've waited for 10 minutes when setting the sleep to 3 seconds and it still did not return. I'll let you know what the debug output is in a bit but you are right there was multiple debug output.

**Comment by MaximGurschi** [comment]
Indeed the OnError is called over and over. My conclusion is that Dispose will not succeed if there are callbacks still being executed. Do you agree with that?

When the sleep time is such that it eventually disposes I see the following additional debug output:
2016-04-25 23:|rdkafka#producer-1|METADATA| *******:9092/bootstrap: ===== Received metadata =====
2016-04-25 23:|rdkafka#producer-1|METADATA| *******:9092/bootstrap: ===== Received metadata =====
2016-04-25 23:|rdkafka#producer-1|TERMINATE| *******:9092/bootstrap: Handle is terminating: failed 2 request(s) in retry+outbuf 

I do not see output like that when the Sleep is long enough. Not sure if this helps or not though.

My plan was to Dispose of the client if i detect that all brokers are down and create a new connection to a different cluster. I guess i could just keep the old client around but it is a bit counter-intuitive that Dispose would be blocked on callbacks. The other way i guess if for me to offload any long processing in callbacks. In general is it correct that calling the API from different threads, callbacks is correct?

**Comment by ah-** [comment]
That sounds sensible. Dispose will wait forever if new callbacks are enqueued faster than old ones are processed. I'd suggest doing what you say and offloading long processing and only triggering the processing once instead of doing it over and over again on every OnError. Then this shouldn't be an issue at all.

Not sure about the debug output, but it does look ok as far as I can tell.

**Comment by MaximGurschi** [comment]
To close out this question can you please let me know about what is the best way to detect that (any subset of) the cluster is available again after the AllBrokerDown event?

Once OnError triggers saying that all brokers are down, the way i detect that the cluster is back is by checking when was the last time that AllBrokerDown happened:
1.If OnError indicates AllBrokerDown then i record the time. 
2.If there is a repeat AllBrokerDown then i update the time
3.Next time i want to use the client i check the time recorded above.
4.If the time is older than 20 seconds ago then i consider the cluster to be back online.

What do you think of this? Is there a proper way to achieve this?

**Comment by ah-** [comment]
I think waiting for AllBrokersDown to disappear is currently the best way to deal with it. Alternatively you could just try sending messages or doing other calls and wait until that stops failing.

I believe librdkafka actually has a pretty good model internally that you can see if you enable debug logging, but it's not exposed at the moment. Maybe open a librdkafka issue to request that, I'd be happy to implement C# bindings.

**Comment by MaximGurschi** [comment]
Thanks for that!
