### ISSUE TITLE
RdKafka nuget>0.9.1-ci-111 no longer copies native librdkafka binaries

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#35]
Hello,

After the release of nuget package 0.9.1-ci-116, RdKafka stopped creating x64, x86 folders when you build the project. This means that RdKafka can no longer find the native dll at runtime. Can you please bring that feature back?
I can confirm that this was introduced with (0.9.1-ci-116).

Related issue:
[[https://github.com/ah-/rdkafka-dotnet/issues/34]](url)

**Comment by MaximGurschi** [comment]
Do you think you will be able to fix that? Or will you leave it as is and we should handle the native binaries ourselves?

**Comment by ah-** [comment]
Will fix, just haven't had the time to do it. I'll have a look this weekend.

**Comment by ah-** [comment]
Fixed now in RdKafka.0.9.1-ci-132 / RdKafka.Internal.librdkafka.0.9.1-ci-16.

There's a .props file in RdKafka.Internal.librdkafka (https://github.com/ah-/librdkafka-package/blob/master/src/RdKafka.Internal.librdkafka/build/RdKafka.Internal.librdkafka.props) which does the copying automatically but it stopped getting picked up due to a package name change.

**Comment by MaximGurschi** [comment]
Thank you!
