### ISSUE TITLE
Topic.Produce may hang when queue is full

### ISSUE THREAD

**Issue by treziac** [ah-/rdkafka-dotnet#52]
If librdkafka temporarily lose connexion to brokers (network failure) and hit local queue size limit,  Topic.Produce will stay in a loop until messages time out (as handle.Produce  will always fail and set _QUEUE_FULL as last error and thus perform a delay)
```
while (true)
{
    if ((a = handle.Produce(payload, key, partition, GCHandle.ToIntPtr(gch))) == 0)
    {
        // Successfully enqueued produce request
        break;
    }

    ErrorCode err = LibRdKafka.last_error();
    if (err == ErrorCode._QUEUE_FULL)
    {
        // Wait and retry
        Task.Delay(TimeSpan.FromMilliseconds(50)).Wait();
    }
. . .
}
```
Produce is supposed to be non blocking, maybe remove the loop, throw the exception and let user handle it, or is there any good reason for this loop?

**Comment by ah-** [comment]
The main reason for this loop is simplicity, it makes sure that by default everything you produce will be delivered and that you don't need to handle the edge case of a full queue yourself. Otherwise it's easy to write code that works during testing with a little bit of data and then starts failing when you push a lot of data through.

In the current development branch of librdkafka Magnus added a flag to support that behaviour directly: https://github.com/edenhill/librdkafka/commit/f7a7a1df6a4efd88265c0d4768ee5c4f5036cba4

My preferred resolution of this would be to remove the loop and expose support for RK_MSG_BLOCK instead once it is released in the next librdkafka.

If you want this earlier I'd be happy to merge a PR that implements the same thing by just making the loop optional. Just add a flag block=True to Produce and skip the loop if it's set. Then we can switch it over to use RK_MSG_BLOCK internally once that's released.

Looking at https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html it seems that the Java producer blocks by default so I think we should do the same in .net.

**Comment by treziac** [comment]
Forgot to answer, thanks :) will see how it will evolve on edenhill side. If the problem happen on my side during more advanced test i'll do a PR
