### ISSUE TITLE
Expose more config options as Properties

### ISSUE THREAD

**Issue by ah-** [ah-/rdkafka-dotnet#8]
https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/Config.cs#L30 already exposes a few config options in a very native-feeling way. Add more commonly used config options.

**Comment by edenhill** [comment]
It is my absolutely strongest suggestion to create a very thin configuration layer on top of librdkafka's `,,conf_set(, .."key", "value", ..)` API.

Why?:
 * Your bindings automatically supports all librdkafka configuration values with no extra work on your side
 * librdkafka's documentation can be used
 * librdkafka's config properties aim to be as similar to the official java client
 * Simply upgrading the shared library will automatically provide new configuration properties to the user. One example of this is when SSL and SASL was added, they were two quick large features that all existing clients got for free since they were simply configuration based (no new APIs).

**Comment by edenhill** [comment]
(unrelated: your URL links all miss their dots/periods)

**Comment by klimchuk** [comment]
I don't understand how to set queue.buffering.max.ms 
```
                    TopicConfig config = new TopicConfig();
                    config["queue.buffering.max.ms"] = "200";
```
returns No such configuration property: "queue.buffering.max.ms"
It obviously exists in librdkafka https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by ah-** [comment]
queue.buffering.max.ms is one of the global configuration properties, so you need to set it on a Config instance:
```
Config config  = new Config();
config["queue.buffering.max.ms"] = "200";
```

**Comment by klimchuk** [comment]
It worked! Thank you very much!
